### ISSUE TITLE
关于签名里面的问题

### ISSUE THREAD

**Issue by echobygo** [yanue/starkex#1]
NetworkId:          NETWORK_ID_MAINNET,
		CreditAmount:       "1",
		DebitAmount:        "2",
		SenderPositionId:   12345,  //这些参数是什么意思？
		ReceiverPositionId: 67890,//这些参数是什么意思？ 
		ReceiverPublicKey:  "04a9ecd28a67407c3cff8937f329ca24fd631b1d9ca2b9f2df47c7ebf72bf0b0",//这些参数是什么意思？
		ReceiverAddress:    "0x1234567890123456789012345678901234567890",//这些参数是什么意思？
		Expiration:         "2020-09-17T04:15:55.028Z",
		ClientId:           "This is an ID that the client came up with to describe this transfer",

**Comment by yanue** [comment]
api接口:  https://docs.dydx.exchange/#create-fast-withdrawal
python原始实现: https://github.com/dydxprotocol/dydx-v3-python/blob/61dc8d49ce2632a800b6d77e55455d2cd4d369c5/dydx3/starkex/conditional_transfer.py#L32
解释: 
获取账户信息里面有PositionId,
SenderPositionId: 自己的,
ReceiverPositionId: lpPositionId
ReceiverPublicKey: lp_stark_public_key
ReceiverAddress: to_address, Address to be credited
