### ISSUE TITLE
Add more support for additional markets.

### ISSUE THREAD

**Issue by itsahedge** [yanue/starkex#3]
Currently, the `SYNTHETIC_ID_MAP` and `ASSET_RESOLUTION` don't include a lot of the newly added markets on DYDX as shown in the v3-python implementation: https://github.com/dydxprotocol/dydx-v3-python/blob/dc7705ed51891c4901f26bfed9ca91a0e95ce1aa/dydx3/constants.py#L61

Please add support for all the markets as we cannot submit Orders because the signature fails on non-supported markets as outlined in the `constants.go` file
https://github.com/yanue/starkex/blob/master/const.go

**Comment by yanue** [comment]
the `SYNTHETIC_ID_MAP` and `ASSET_RESOLUTION `are now defined in the new file:
https://github.com/yanue/starkex/blob/master/assets.go
and support for all the markets.
