### ISSUE TITLE
create new order 签名错误？？？

### ISSUE THREAD

**Issue by nntaoli** [yanue/starkex#4]
2022/08/22 00:35:35 {NetworkId:3 PositionId:1 Market:ETH-USD Side:BUY HumanSize:0.1 HumanPrice:1500 LimitFee:0.01 ClientId:8141797145391901 Expiration:2022-08-21T16:40:35.548Z}
2022/08/22 00:35:35 https://api.stage.dydx.exchange/v3/orders
go-dydx 2022/08/22 00:35:36 uri: /v3/orders, code: 400, err msg: {"errors":[{"msg":"Invalid signature for order"}]}

**Comment by yanue** [comment]
测试是ok的, 注意stark_private_key是否正确

**Comment by nntaoli** [comment]
已解决，positionId问题，谢谢
