### ISSUE TITLE
Support for goerli network

### ISSUE THREAD

**Issue by emil14** [yanue/starkex#5]
dydx/starkex [moved](https://docs.starkware.co/starkex/starkex_playground_tutorial.html) to [goerli](https://goerli.net/) network. Current starkex package doesn't support it. Is it possible to add such support?

```go
	orderSignParam := starkex.OrderSignParam{
		NetworkId: 5, // dydx testnet
                // ...
	}

	signature, err := starkex.OrderSign(starkexCredsPrivateKey, orderSignParam)
	if err != nil {
		return err // <- here
	}
```

This is the source of error - https://github.com/yanue/starkex/blob/master/sign_order.go#L36

**Comment by yanue** [comment]
just check this:  https://github.com/yanue/starkex/commit/5c922d20a0d494bb5d841ad10b7142b22e324bf1
but I don't know if it works or not.

**Comment by emil14** [comment]
but the problem is in `COLLATERAL_ASSET_ID_BY_NETWORK_ID` map, not `ASSET_RESOLUTION`
