### ISSUE TITLE
关于 order 签名的效率问题

### ISSUE THREAD

**Issue by lzmhhh123** [yanue/starkex#6]
使用 golang 通过 grpc 调用官方 python 的 https://github.com/dydxprotocol/dydx-v3-python  
与直接调用该库进行延时对比，发现该库的延迟是官方 python 包的一倍。

![image](https://user-images.githubusercontent.com/26040259/217474472-a6eca51d-7ad1-44dd-ab36-86469de36b44.png)

多次测试均差不多为该结果。

**Comment by lzmhhh123** [comment]
@yanue 找不到你的联系方式，如果能探讨优化，欢迎联系我

**Comment by yanue** [comment]
目前发现主要耗时在2个地方: 

1. PedersenHash中循环处理(100ms左右),已采用并行处理
2. doSign中的ecMult在递归计算(387次100ms左右),这个没办法处理

处理后总耗时大约在100ms左右
