### ISSUE TITLE
How to use the signature generator for dydx exchange ?

### ISSUE THREAD

**Issue by Danielhodali** [yanue/starkex#8]
I installed the signature generator for dydx exchange, but I don't how to use it.

**Comment by yanue** [comment]
just see readme

**Comment by Danielhodali** [comment]
package main

import "fmt"

func main() {

	const MOCK_PRIVATE_KEY = "58c7d5a90b1776bde86ebac077e053ed85b0f7164f53b080304a531947f46e3"
	param := OrderSignParam{
		NetworkId:  NETWORK_ID_ROPSTEN,
		Market:     "ETH-USD",
		Side:       "BUY",
		PositionId: 12345,
		HumanSize:  "145.0005",
		HumanPrice: "350.00067",
		LimitFee:   "0.125",
		ClientId:   "This is an ID that the client came up with to describe this order",
		Expiration: "2020-09-17T04:15:55.028Z",
	}
	sign, err := OrderSign(MOCK_PRIVATE_KEY, param)
	// 00cecbe513ecdbf782cd02b2a5efb03e58d5f63d15f2b840e9bc0029af04e8dd0090b822b16f50b2120e4ea9852b340f7936ff6069d02acca02f2ed03029ace5
	fmt.Println("sign,err", sign, err)
}

OderSign is unknown

**Comment by Danielhodali** [comment]
I seems that I  have an issue with importing the signature generator library. Can you help?

**Comment by yanue** [comment]
you need add:

```import "github.com/yanue/starkex"```

also you can see how to use in :

https://github.com/go-numb/go-dydx/blob/master/private/request.go#L44C1-L45C1
